[workspace]
authors = ["noorabozawa <noorabozawa@gmail.com>"]
channels = ["conda-forge"]
name = "BINF-5507-Winter-2026"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
ipykernel = ">=7.1.0,<8"
numpy = ">=2.4.1,<3"
pandas = ">=2.3.3,<3"
